#===============================================================================================================================#
'''Script Kiddies First Python Program'''
#===============================================================================================================================#

#As a new programmer you might be refered to as a Script Kiddie, 
#This is a programmer joke to describe someone who does not know much about programming
#Script Kiddies often use code they do not understand written by other programmers

#Welcome to the Python Programming Language.
#Python is an interpreted procedural object oriented programming language
#Python files have the (.py) extension.

#===============================================================================================================================#
'''
Covered in this file:
> Single/Multi Line Comments
> First Program: Console Output
> First Program: User Input
> Executing Python Programs
'''

#===============================================================================================================================#
'> Single/Multi Line Comments'

# use a hash tag to make a single line python comment

'''
use three single quotes to make a 
  multi
    line 
      comment 
          called 
                a 
                  docstring
'''

# Use
# Ctrl + /
# to make quick multi-line comments
# or to comment out a single line easily

#===============================================================================================================================#
'> First Program: Console Output'

#To build your first program
#Use the built-in print() function call to send output to the console
print("Hello World") 
# text must be written in quotes and is called a string. 
#===============================================================================================================================#
'> First Program: User Input'

#To build your first program
#Use the built-in input() function call to accept input from a user
# input()

#Place a string of text inside the input() function call to prompt the user
# input("Type your input: ")

#If you place the input() function call inside of the  print() function call to see the input output
print(input("Type your input: ")) 
# text must be written in quotes and is called a string. 
#===============================================================================================================================#
'> Executing Python Programs'

'''
Congrats you have written your first python program!

  Scource code like this is compiled into byte code by the python interpreter (python.exe on windows|python3 on linux/MacOS).
    Then the python virtual machine PVM executes the bytecode instructions one by one.


Python Programs can be executed by invoking the interpreter through the command prompt or python shell.

  Python is installed by default here C:\Program Files\Python3xx on Windows depending on the version installed.
  Python may also be installed here for a specific user: C:\Users\%USERPROFILE%\AppData\Local\Programs\Python\Python3xx
    To check the current version type the following on the command line interface

      python --version

    To execute .py files on windows type the following on the command line interface

      python filename.py


    
  Python is installed by default here /usr/bin/python3 on Linux/MacOS depending on the version installed. 
    To check the current version type the following on the command line interface

      python3 --version
      
    To execute .py files on linux and Mac type the following on the command line interface

      python3 filename.py

'''


#===============================================================================================================================#
''' Vocabulary:

Byte code
Command Line Interface (CLI)
Command Prompt
Comments
Compile
Console
Docstring
Function Call
Interpreter
Object Oriented
Procedural
Program
Python Shell
Python Virtual Machine (PVM)
Scource Code
String

Byte code:
Byte code is the intermediate representation of a program generated by a compiler or an interpreter. 
It is a low-level, platform-independent format that can be executed by a virtual machine.

Command Line Interface (CLI):
A Command Line Interface (CLI) is a text-based interface used to interact with a computer program or operating system by typing commands into a terminal or console.

Command Prompt:
A command prompt is a specific type of text-based interface in a CLI where the user can enter commands to interact with the system. 
It usually displays a prompt indicating that the system is ready to accept commands.

Comments:
Comments are non-executable lines of text in a program used to provide explanations, notes, or documentation to make the code more understandable to humans. 
Comments are ignored by the interpreter or compiler when the code is executed or compiled.

Compile:
Compilation is the process of translating source code written in a high-level programming language into machine code or byte code that can be executed by a computer. 
Compiled languages typically produce executable files that can be run directly by the operating system.

Console:
A console is a text-based interface for interacting with a computer program or system. 
It typically consists of a command prompt or terminal window where users can enter commands and view text-based output.

Docstring:
A docstring is a string literal enclosed in triple quotes used to provide documentation for functions, classes, modules, or methods in Python. 
Docstrings are accessible via the __doc__ attribute and are commonly used to describe the purpose, usage, and behavior of the code.

Function Call:
A function call is an instruction that tells the program to execute a specific function with certain arguments. 
When a function is called, control is transferred to the function's code, and the function's return value (if any) is passed back to the caller.

Interpreter:
An interpreter is a program that executes source code directly, line by line, without the need for prior compilation. 
Interpreters are commonly used in scripting languages like Python, where the source code is executed dynamically at runtime.

Object Oriented:
Object-oriented programming (OOP) is a programming paradigm that organizes software design around objects, which are instances of classes that encapsulate data and behavior. 
OOP emphasizes concepts such as encapsulation, inheritance, and polymorphism.

Procedural:
Procedural programming is a programming paradigm that focuses on writing procedures or routines that perform specific tasks. 
It emphasizes procedures, or sequences of statements, that manipulate data and control program flow.

Program:
A program is a set of instructions written in a programming language that specifies how a computer should perform a particular task or solve a problem. 
Programs can range from simple scripts to complex software applications.

Python Shell:
The Python shell, also known as the Python interactive interpreter, is an interactive command-line interface that allows users to enter Python code directly and see the results immediately. 
It is a convenient way to experiment with Python code and test small snippets.

Python Virtual Machine (PVM):
The Python Virtual Machine (PVM) is the runtime engine that executes Python byte code. 
It is responsible for interpreting or executing the byte code produced by the Python compiler and managing memory, objects, and other runtime resources.

Source Code:
Source code is the human-readable version of a program written in a programming language. 
It consists of text-based instructions and declarations that are written by a programmer and can be understood and modified by humans.

String:
A string is a sequence of characters enclosed in single quotes (') or double quotes ("). 
Strings are used to represent textual data in programming and can contain letters, digits, symbols, and whitespace. In Python, strings are immutable, meaning they cannot be changed after they are created.
'''